### ISSUE TITLE
Disabled flag.

### ISSUE THREAD

**Issue by aadrian** [grails-plugins/grails-spring-security-ldap#19]
Please add support for a `disabled` flag that would disable the LDAP functionality, thus performing a local authentication like when the plug-in would not be active at all.

The mail plug-in also offers this kind feature http://gpc.github.io/grails-mail/guide/2.%20Configuration.html#2.3%20Other%20Configuration and it's very useful for local development.

Thank you.

**Comment by burtbeckwith** [comment]
Add `grails.plugin.springsecurity.ldap.active = false` in Config.groovy

**Comment by aadrian** [comment]
@burtbeckwith thank you.

> Add grails.plugin.springsecurity.ldap.active = false in Config.groovy

Nice to see that there's such a feature.

In the documentation is not mentioned however:
https://grails-plugins.github.io/grails-spring-security-ldap/v2/guide/configuration.html

Thank you.
