### ISSUE TITLE
Spring Security LDAP mapper.userDetailsClass setting being ignored in Grails 4 app

### ISSUE THREAD

**Issue by Jonlee2001** [grails-plugins/grails-spring-security-ldap#23]
I am trying to use the spring-security-ldap plugin (3.0.2) in a Grails 4 app with spring-security-core (4.0.0RC2) and wherever I set the ldap.mapper.userDetailsClass = 'inetOrgPerson' flag its being ignored.

I've tried setting it in application.yml

```
plugins:
  springSecurity:
    ldap:
      mapper:
        userDetailsClass: 'inetOrgPerson'
```

and in application.groovy

```
grails.plugin.springsecurity.ldap.mapper.userDetailsClass = 'inetOrgPerson'
```

but neither of them seem to work, as I keep getting this error:

```
No such property: displayName for class: org.springframework.security.ldap.userdetails.LdapUserDetailsImpl
```

Is there another place this should be set? Or am I missing something?

(This all worked fine in an earlier version of this app built in Grails 2.3 and spring-security-core:2.0 and spring-security-ldap:2.0)

**Comment by jdaugherty** [comment]
You need to use the 4.x version of this plugin to be Grails 4 compatible.
