### ISSUE TITLE
Grails 4 support?

### ISSUE THREAD

**Issue by eshton** [grails-plugins/grails-spring-security-ldap#24]
Hi @burtbeckwith !

I would like to use this plugin in Grails 4. Do you think it would be hard to make the upgrade?

Thanks in advance.

**Comment by sdelamo** [comment]
I've released a milestone version which should compatible with Grails 4. 

```groovy

repositories {
    ...
    maven { url "https://dl.bintray.com/grails/plugins" }
}

dependencies {
       compile ("org.grails.plugins:spring-security-ldap:4.0.0.M1")
       ....
}
```
